# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-14 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read'),
        ),
    ]
