# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20151205_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nick',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nick'),
        ),
    ]
