# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_auto_20151205_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='access_code',
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='Access url'),
        ),
    ]
