# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0003_auto_20151205_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gift',
            old_name='reservetion_date',
            new_name='reservation_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Access url'),
        ),
    ]
