# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0004_auto_20151205_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='reservation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reservation date'),
        ),
    ]
